### PR TITLE
SPM support and multi-platform

### PR DESCRIPTION
**Pull request by ky1vstar**
This PR make BezierKit available trough SPM and buildable on non-Apple platforms (Linux, Windows). Very little changes were made to source files.

Things that don't work on non-Apple platforms:
- CGPath (requires CoreGraphics);
- Draw (requires CoreGraphics);
- Tests  (requires CGPath, so CoreGraphics);

P.S. I think that making BezierKit multi-platform is very cool, because it brings power of bezier curves to Swift in Linux world.

### CODE REVIEW

**Comment by hfutrell** [comment]
@ky1vstar thank you for your contribution!

I'm going to get the continuous integration (Travis-CI) up and running with Swift Package Manager and a Linux environment, and then merge this into the latest release.

I don't use Linux or SPM so the continuous integration will make sure that I don't break this support with future development.

**Comment by hfutrell** [comment]
@ky1vstar ok so the Travis-CI is taking a bit longer than I thought. If you are familiar with Travis-CI I could use help modifying the `.travis.yml` to spin up a linux instance and run `swift test --enable-test-discovery` to execute the tests. I do have the tests running on an Ubuntu install locally.

**Comment by ky1vstar** [comment]
@hfutrell thanks for approving!
Unfortunately I'm not familiar with Travis, but I found a working reference [here](https://github.com/Kitura/Kitura/blob/master/.travis.yml)

**Comment by hfutrell** [comment]
thank you for looking into it. Ultimately I used a lot of trial and error to get things working! I am not good at DevOps ...

So the good news is that continuous integration is working with Linux! I have merged the Swift Package Manager work into the latest release branch.

**Comment by Ceylo** [comment]
I've just seen SPM support in today's release. Just wanted to say this PR is much welcome! I had already moved away from CocoaPods and had manually integrated BezierKit as subproject as it was my last dependency without SPM support. Now I've everything managed through SPM and I'm happy, thank you!

**Comment by ky1vstar** [comment]
@hfutrell I appreciate work you've put into this PR to make it life.
@Ceylo Thank you for kind words, I hope this PR will add more flexibility to evolve this project in future.

**Pull request merged**
